server:
  port: 8081 #端口


# 自定义文件上传路径
web:
    # Linux
    upload-path: /Users/maojunjun/Code/emsdemo/image
    # Windows 10
    # upload-path: C:/Users/SIZ/Desktop/bishe/image/

#spring配置
spring:
    #数据库
    datasource:
        name: opengauss
        username: gaussdb
        password: "Gauss@123"
        url: jdbc:opengauss://39.102.62.113:5432/sports_event_system
        driver-class-name: org.postgresql.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        #Spring Boot 默认是不注入这些属性值的，需要自己绑定
        #druid 数据源专有配置
        druid:
          initial-size: 1
          initialSize: 5
          minIdle: 5
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true

    #国际化配置
    messages:
      basename: i18n.messages


    servlet:
      multipart:
        max-file-size: 2MB
    #thymeleaf 配置
    thymeleaf:
      cache: false
      encoding: utf-8
      mode: HTML5


#mybatis配置
mybatis:
  typeAliasesPackage: com.sizaif.emsdemo.pojo
  mapperLocations: classpath:mybatis/Mapper/*.xml


#分页pageHelper
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true


